version: '3.8'

services:
  alura-recipe-app:
    build: .
    container_name: alura-recipe-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/server
    ports:
      - 8000:8000
  postgresql:
    image: postgres:14-alpine
    container_name: alura-recipe-postgres-db
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: alura_recipe_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
