[tool.poetry]
name = "alura-recipe-app"
version = "0.1.0"
description = ""
authors = ["John Silver <johncarlosilver@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.2"
dynaconf = "^3.1.7"
psycopg2-binary = "^2.9.3"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
black = "^22.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
