# Generated by Django 4.0.2 on 2022-02-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('preparation_mode', models.TextField()),
                ('preparation_time', models.IntegerField()),
                ('income', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
